### ISSUE TITLE
refactor runtests.jl?

### ISSUE THREAD

**Issue by tanmaykm** [dls/DynamoDB.jl#2]
I suppose running the tests will require some sort of AWS keys. Is it possible do all the tests in the CI run?

If not, you may want to remove them from `runtests.jl`, but have them in a separate file that can be run independently.

**Comment by dls** [comment]
Hi Tanmaykm,

Yeah, the integration tests do require AWS keys, which I provide in [integration_tests.jl](https://github.com/dls/DynamoDB.jl/blob/a7282b199dfd01d8a725d6564070c8234bc28e4c/test/integration_tests.jl#L11) (which isn't a problem from my perspective, since I don't mind hosting a DyanmoDB table specifically for testing). See #1

Right now running test/runtests.jl or Pkg.test("DynamoDB") will run everything (both for you locally, or on TravisCI/Appveyor), and requires no special configuration on your part. I must admit I really like this setup, since it means any integration errors will be caught by TravisCI rather than some poor user, and there's one less file to run / thing to remember for any contributors.

Another option would be supporting [DynamoDB Local](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/Tools.DynamoDBLocal.html). This might be helpful for people using DynamoDB.jl as a library in addition to the integration tests, but including it seemed too board/ambitious a goal for the initial release -- I have to admit I'm still reading through the BinDeps package documentation :p

**Comment by tanmaykm** [comment]
I think it is best to plug in DynamoDB local for the tests. The test fails to run (fails to connect to server) on my local machine.

Having the keys to any real table around is not going to work. Nothing prevents someone to use it for a purpose other than this test. You can potentially run up a huge bill as a result of that.

**Comment by tanmaykm** [comment]
Ok, they seem to be going through this time.
But it is still best to have the local DynamoDB instead, for reasons mentioned above.

**Comment by aviks** [comment]
Note that for CI, Travis supports secure properties: http://docs.travis-ci.com/user/environment-variables/#Defining-Variables-in-Repository-Settings

**Comment by dls** [comment]
@tanmaykm 

Could you tell me what the error was when it failed to connect to the server? That sounds like potentially an error in the code.

Pricing for DynamoDB tables is actually fixed (it's pay by throughput, not pay by API call), so the cost of putting that API key in the code is the same (assuming you periodically vacuum out the test table, which I'd be doing anyway because test failures result in orphaned rows)

@aviks

I could add a check for ENV["AWS_KEY"] or whatever, but then random people couldn't easily verify things were working. I'll spend more time on DynamoDB local, I'm starting to feel like I committed some major taboo here... does the developer community basically not trust IAM permissions to work correctly? I feel like I must have missed some major blog post or something.

**Comment by tanmaykm** [comment]
Here's what I saw:

```
ERROR: LoadError: LoadError: "Error executing request : Couldn't connect to server"
 [inlined code] from strings/basic.jl:17
 in exec_as_multi at /home/tan/.julia/v0.5/HTTPClient/src/HTTPC.jl:717
 in _put_post at /home/tan/.julia/v0.5/HTTPClient/src/HTTPC.jl:499
 in put_post at /home/tan/.julia/v0.5/HTTPClient/src/HTTPC.jl:469
 in post at /home/tan/.julia/v0.5/HTTPClient/src/HTTPC.jl:403
 in dynamo_execute at /home/tan/.julia/v0.5/DynamoDB/src/dynamo_requests.jl:85
 in delete_item at /home/tan/.julia/v0.5/DynamoDB/src/dynamo_row_ops.jl:417
 [inlined code] from /home/tan/.julia/v0.5/DynamoDB/src/dynamo_row_ops.jl:415
 in anonymous at no file:0
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:392
 in include at ./boot.jl:261
 in include_from_node1 at ./loading.jl:392
 in process_options at ./client.jl:277
 in _start at ./client.jl:377
while loading /tmp/DynamoDB.jl/test/integration_tests.jl, in expression starting on line 103
while loading /tmp/DynamoDB.jl/test/runtests.jl, in expression starting on line 17
```

**Comment by dls** [comment]
@tanmaykm thanks!

**Comment by aviks** [comment]
I don't have any opinion on the security of IAM keys. I was only suggesting options, given Keno's comment on the other bug that Amazon disables keys found on Github.

**Comment by dls** [comment]
@aviks Amazon did end up emailing me, and I explained the above to them. The IAM key will continue to function. Strange timing, as those AWS credentials have been on github for two weeks now.

@tanmaykm everything I've found on that error indicates a network hiccup (TCP handshake failure). I've gone ahead and updated the code to include those in the list of things which should be retried rather than cause an explosion. Thanks again!
